name: Sync to gitee
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 同步到 gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SERVER_KEY }}
        with:
          source-repo: git@github.com:ahyiru/file-system.git
          destination-repo: git@gitee.com:yiru/file-system.git
